import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
      <body>
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
  );
}
